set MATLAB=D:\Program Files\MATLAB\R2013b
"D:\PROGRA~1\MATLAB\R2013b\bin\win32\gmake" -f test_mdl.mk  EXTMODE_STATIC_ALLOC=0 EXTMODE_STATIC_ALLOC_SIZE=1000000 TMW_EXTMODE_TESTING=0 OPTS="-DON_TARGET_WAIT_FOR_START=0"
